### ISSUE TITLE
Terraform Meraki Provider AzureRM

### ISSUE THREAD

**Issue by Crallbit** [core-infra-svcs/terraform-provider-meraki#249]
Hi everyone,

first of all, thanks for this Community. :)

I would like to know if it is possible to deploy Meraki vmx from Terraform to Azure, thanks

**Comment by iamdexterpark** [comment]
I believe this would be a great addition to the organization resource. It appears there are some API endpoints specific to vmx provisioning that are required to support this use-case:  

- "/devices/{serial}/appliance/vmx/authenticationToken"
- "/networks/{networkId}/devices/claim/vmx"

Unfortunatly, this hasn't been developed yet, and I am unable to provide an ETA at this time. If there are any developers interested in assisting with this project I would be happy to work with them in order to begin developing this feature.
